-- 02_schema_orders.sql
-- Transactional Tables with PARTITIONING

-- 1. ORDERS TABLE (Master Table)
-- We use RANGE partitioning on 'created_at'
CREATE TABLE orders (
    order_id UUID NOT NULL, -- UUID not default here, generated by App or trigger
    customer_email VARCHAR(100) NOT NULL,
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) CHECK (status IN ('PENDING', 'CONFIRMED', 'SHIPPED', 'CANCELLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Partition key must be part of the primary key logic
    PRIMARY KEY (order_id, created_at)
) PARTITION BY RANGE (created_at);

-- 2. CREATE PARTITIONS (Example for 2024-2025)
-- In production, you would have a cron job create these automatically.

CREATE TABLE orders_y2024m10 PARTITION OF orders
    FOR VALUES FROM ('2024-10-01') TO ('2024-11-01');

CREATE TABLE orders_y2024m11 PARTITION OF orders
    FOR VALUES FROM ('2024-11-01') TO ('2024-12-01');

CREATE TABLE orders_y2024m12 PARTITION OF orders
    FOR VALUES FROM ('2024-12-01') TO ('2025-01-01');
    
-- Default partition for future dates/catch-all
CREATE TABLE orders_default PARTITION OF orders DEFAULT;

-- 3. ORDER ITEMS
-- We link this to orders.
CREATE TABLE order_items (
    item_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL,
    order_created_at TIMESTAMPTZ NOT NULL, -- Needed for FK to partitioned table
    product_id UUID REFERENCES products(product_id),
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price DECIMAL(10,2) NOT NULL,
    
    -- Foreign Key pointing to the partitioned parent
    FOREIGN KEY (order_id, order_created_at) REFERENCES orders(order_id, created_at)
);

-- 4. DEMAND FORECAST (AI Output Table)
CREATE TABLE demand_forecast (
    forecast_id SERIAL PRIMARY KEY,
    product_id UUID REFERENCES products(product_id),
    forecast_date DATE NOT NULL,
    predicted_demand INT NOT NULL,
    confidence_interval_lower INT,
    confidence_interval_upper INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);